### ISSUE TITLE
Buy airtime for Others Option is missing 

### ISSUE THREAD

**Issue by Alfredbis29** [cedricbahirwe/dialer#86]
-  I noticed that the `Buy airtime for Others` option is missing from the app, and I believe this feature is essential for many of your users who often purchase airtime for their friends and family :wink: 

I would appreciate it if you could check into this situation and provide a solution as soon as you can. I appreciate the prompt reply you provided to this matter.

**Comment by cedricbahirwe** [comment]
Thanks for the feedback @Alfredbis29 , however, after research I found that not so many people perform such operations (buying airtime for other people), It is often a one-time thing that

**Comment by cedricbahirwe** [comment]
Not enough feature requests
